### PR TITLE
Add ARM OS X 

### PR DESCRIPTION
**Pull request by jonashaag**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jonashaag** [comment]
@conda-forge-admin rerender

**Comment by jonashaag** [comment]
@conda-forge-admin rerender

**Comment by wolfv** [comment]
We already have it! https://anaconda.org/conda-forge/ccache :) Did it not work?

**Comment by jonashaag** [comment]
Umm... true, didn't see that! I was confused because it didn't build locally but that was due to `findutils-feedstock` being outdated.

**Comment by wolfv** [comment]
right. you tried a native build, but in the CI `findutils` was used from `osx-64` in the `build` environment. I think we can close this, correct?

**Pull request closed without merging**
